# codeflow/docker-compose.yml
services:
    spring:
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: codeflow-spring
        expose:
            - "8001"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
            SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
            SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
            SPRING_DATA_REDIS_HOST: redis
            SPRING_DATA_REDIS_PORT: 6379
            SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}
            SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
            SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
            JWT_SECRET: ${JWT_SECRET}
            GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
            GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
            OAUTH2_REDIRECT_URI: ${OAUTH2_REDIRECT_URI}
            GOOGLE_GEMINI_API_KEY: ${GOOGLE_GEMINI_API_KEY}
            DOCKER_NETWORK: proxy
        restart: unless-stopped
        networks:
            - proxy

networks:
    proxy:
        external: true
        name: proxy